# Generated by Django 5.2.8 on 2026-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_subcategory_blog_chead0_blog_chead1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
