# Generated by Django 5.2.8 on 2026-01-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orders_phone_alter_orders_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
